# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
xcversion(version: "16.4.0")

platform :ios do
  #desc "Generate new localized screenshots"
  #lane :screenshots do
  #  capture_screenshots(scheme: "readeck")
 # end

  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(scheme: "readeck")
    upload_to_testflight
  end
end


